### ISSUE TITLE
Can you provide Some examples using Request parameters at Docs?

### ISSUE THREAD

**Issue by sperezm97** [samueldaviddelacruz/dr-oil-prices-api#1]

**Comment by samueldaviddelacruz** [comment]
@sperezm97 

I think the doc is well documented on which query parameters can be sent for any given path, but here are some examples just in case:

https://fy2imwzr1f.execute-api.us-west-2.amazonaws.com/dev/oil-prices  //will retrieve all oil prices stored till last measure date.

https://fy2imwzr1f.execute-api.us-west-2.amazonaws.com/dev/oil-prices?startDate=1563508800000&endDate=1564718400000  //will retrieve all the oil prices between the startDate and the endDate (both in milliseconds).

**Comment by sperezm97** [comment]
Thanks
